# Generated by Django 3.2.12 on 2022-02-17 08:45

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False,
                                          verbose_name='UUID')),
                ('create_time', models.DateTimeField(default=1645087525.927577, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(verbose_name='更新时间')),
                ('name', models.CharField(max_length=64, verbose_name='书籍名称')),
                ('author', models.CharField(max_length=64, verbose_name='作者')),
                ('intro', models.CharField(blank=True, max_length=512, verbose_name='简介')),
                ('words_num', models.IntegerField(null=True, verbose_name='字数')),
                ('chapter_latest', models.UUIDField(null=True, verbose_name='最新章节')),
            ],
            options={
                'db_table': 't_da_book',
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False,
                                          verbose_name='UUID')),
                ('create_time', models.DateTimeField(default=1645087525.927577, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(verbose_name='更新时间')),
                ('chapter_no', models.IntegerField(null=True, verbose_name='章节编号')),
                ('name', models.CharField(max_length=64, verbose_name='章节名称')),
                ('content', models.TextField(null=True, verbose_name='章节内容')),
                ('words_num', models.IntegerField(null=True, verbose_name='字数')),
            ],
            options={
                'db_table': 't_da_chapter',
            },
        ),
    ]
